### ISSUE TITLE
Frontend TODOs

### ISSUE THREAD

**Issue by yoyo930021** [Disfactory/Disfactory#2]
### 一般頁面

- [x] 常用元件 #70 
- [x] Sidebar Layout #143 
- [ ] 靜態頁面 (文案請參考 #66 )
  - [ ] 使用教學
  - [x] 安全須知
  - [x] 聯絡我們連結
  - [x] 關於舉報系統
  
### 顯示工廠列表

- [x] 顯示工廠列表 #32 
- [x] 篩選清單 (連 navbar 元件一起弄) #72 
- [x] Map 元件 #92 
	- 叫出篩選按鈕
	- 定位到 center 按鈕
		- https://openlayers.org/en/latest/examples/geolocation.html
	- zoom in/out 按鈕
- [x] 切換地圖底圖按鈕 (衛星/OSM) related #120 
   
### 新增工廠流程

- [x] 因時間因素有修改一些 MVP 的 Spec #73
- [x] map components #96 
- [x] iPhone 上傳圖片處裡 #144 

### 修改工廠資料

- [x] 點選工廠圖示顯示 Popover #78 
- [x] 點擊補充資料進入工廠修改流程 (只有照片名稱類型其它資訊) #103 
	- 修改以下欄位：
	    - 工廠名稱
	    - 工廠類型
	    - 其它資訊
	- 接 update factory api
- ~~修改單一欄位時其它欄位 disabled~~ 再說(?
- [x] 新增圖片
- ~~更新欄位成功 modal~~
- [x] map components #96

**Comment by aelcenganda** [comment]
20191127 版本 UI
https://zpl.io/VkzYWkK
