### ISSUE TITLE
Backend API TODO

### ISSUE THREAD

**Issue by stegben** [Disfactory/Disfactory#31]
## [Create Factory](https://github.com/Disfactory/Disfactory/blob/master/backend/api/views/factories_cr.py#L69) 
@stegben @ Andy
- [x] Validate post body  #45
- [x] Create `Factory` object.  #50 
- [x] Modify factory reference of all uploaded images  #50 
- [x] Get land code. May ask @pm5 @thehyyu for help.  #50 
- [x] Create a `ReportRecord`  #50 

## [Update Factory](https://github.com/Disfactory/Disfactory/blob/master/backend/api/views/update_factory_attribute.py#L6)
@Simon
 #52 
- [x] Validate post body. TODO: determine which fields are immutable
- [x] Update the specific factory
- [x] Create a `ReportRecord`

## [Upload Image](https://github.com/Disfactory/Disfactory/blob/master/backend/api/views/post_image.py#L8)
@stegben @thehyyu @星翰 @Loooffy 
- [x] Upload to Imgur and get the url  #38 
- [x] Create a `Image`  #56 

## [Upload Image specific to factory](https://github.com/Disfactory/Disfactory/blob/master/backend/api/views/post_factory_image.py#L8)
@stegben @thehyyu @星翰 @Loooffy 
- [x] Upload to Imgur and get the url  #38 
- [x] Create a `Image` referenced to the specific factory  #56 
- [x] Create a `ReportRecord`  #56
